main:
  debug_bijection: false
  compute_metrics: true
  plot: true

model:
  #directory: '/home/simon/Repositories/data/esp_train_results/2023-09/09-11-21-40-02_carla_town01_A1_T20_v2_precog.bijection.social_convrnn.SocialConvRNN_' #single working
  #directory: '/home/simon/Repositories/data/esp_train_results/2023-09/09-12-22-19-08_carla_town01_A1_T20_v2_precog.bijection.social_convrnn.SocialConvRNN_' #multi wrong translation
  #directory: '/home/simon/Repositories/data/esp_train_results/2023-09/09-13-06-41-07_carla_town01_A1_T20_v2_precog.bijection.social_convrnn.SocialConvRNN_' #multi single epoch
  #directory: '/home/simon/Repositories/data/esp_train_results/2023-09/09-13-06-44-48_carla_town01_A1_T20_v2_precog.bijection.social_convrnn.SocialConvRNN_' #multi
  #directory: '/home/simon/Repositories/data/esp_train_results/2023-11/11-14-21-54-09_carla_town01_A1_T20_v2_precog.bijection.social_convrnn.SocialConvRNN_'
  #directory: '/home/simon/Repositories/data/esp_train_results/2023-11/11-26-11-10-38_carla_town01_A1_T20_v2_precog.bijection.social_convrnn.SocialConvRNN_'
  #directory: '/home/simon/Repositories/data/esp_train_results/2023-11/11-26-12-02-16_carla_town01_A1_T20_v2_precog.bijection.social_convrnn.SocialConvRNN_'
  #directory: '/home/simon/Repositories/data/esp_train_results/2023-12/12-03-20-24-40_carla_town01_A1_T20_v2_precog.bijection.social_convrnn.SocialConvRNN_'
  directory: '/home/simon/Repositories/data/esp_train_results/2023-12/12-04-17-23-27_carla_town01_A1_T20_v2_precog.bijection.social_convrnn.SocialConvRNN_'

hardware:
  allow_growth: true
  per_process_gpu_memory_fraction: 0.3
      
hydra:
  job_logging:
    handlers:
      console:
        level: INFO
      file:
        level: DEBUG
  run:
    dir: /home/simon/Repositories/data/esp_infer_results/${now:%Y-%m}/${now:%m-%d-%H-%M-%S}_${dataset.class}

images:
  ext: 'jpg'
  figsize: [4, 4]

split: 'test'

dataset:
  plot_allchannel: false

plotting:
  bev_kwargs:
    onechannel: False
    allchannel: False
    fmt: 'carla'

defaults:
  - dataset: nuscenes_dataset
